### ISSUE TITLE
"add suffix" is not retained

### ISSUE THREAD

**Issue by QGtKMlLz** [Pascal-Krenckel/CompressedFileViewer#2]
Hi, I'm just trying out and was experimenting with adding suffixes.
If I add .xztxt to the xz dialog and close notepad++ and reopen the .xztxt suffix is not retained (gone), and it does not auto decompress a .xztxt file.

The reason I was thinking about this is because I didn't want change the file associations in Win10 File explorer from 7zip or Windows default zip.  I thought I can make

I tried in Admin mode and standard.
I've tried with NPP~Settings~File Associations~.xztxt  added and without it added.
I also tried resetting privileges on the NPP\plugins\CompressedFileViewer folder to "Full Control" and replaced child objects permissions for my user, I am also the owner (which is a way to bypass UAC folder access restriction, since I like to have UAC enabled).
NPP v8.6.9 x64

**Comment by Pascal-Krenckel** [comment]
Hm, I think I forgot to publish the latest version. I remember fixing that problem (I just forgot to save the settings :D). Let me check.

**Comment by Pascal-Krenckel** [comment]
Ok, yeah I did fix this already. Also the error was different then what I remebered. I didn't update the default version number (v2->v3) of Preferences so when loading them, the xz settings (v3) where overridden by the default settings.
I uploaded the latest version. You have to enable the compression algorithms you want in the settings.

Btw doesn't N++ add a context menu entry to open a file with it. So you should be able to right click on any .xz file to open it in N++.

**Comment by QGtKMlLz** [comment]
Yep you were right, my entries showed up by themselves with the new release.

Yep it does have the context menu, but trying this xxxtxt extension and associating it should just allow a double-click, I'm big on efficiency, I've couldn't handle it if my Notepad++ customizations disappeared and would take the day to rebuild and assign icons to toolbar items, and rearrange.
Also with the txt suffix it makes it easier to determine if it's text or an archive in folders with mixed content.   I was also going with the assumption, it I enabled 'Try to decompress all files' it would impact loading time (applications & file), particularly since I have it retain/restore my session.
