### ISSUE TITLE
Notepad++ is not starting with compressedfileviewer in the plugin directory.

### ISSUE THREAD

**Issue by mrx1983** [Pascal-Krenckel/CompressedFileViewer#3]
Have tried the newest v8.7.4 notepad++, tried the older 8.6.6.
tried portable and installed version.
i also tried different versions of the plugin.
i installed asp.net core v8.0.11 runtime.
everything as x64 versions on windows 10.
and it just not starts with the plugin in the plugin folder.
do i miss something?

**Comment by Pascal-Krenckel** [comment]
Please check the folder structure, the path should be: %NotepadDir%/plugins/CompressedFileViewer the final folder must have the exact name as the CompressedFileViewer.dll.

**Comment by mrx1983** [comment]
i have done that, this is what eventviewer shows me:

Name der fehlerhaften Anwendung: notepad++.exe, Version: 8.7.4.0, Zeitstempel: 0x6750dcd2
Name des fehlerhaften Moduls: CompressedFileViewer.dll, Version: 0.0.0.0, Zeitstempel: 0x66c396e6
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000000000034b7d
ID des fehlerhaften Prozesses: 0x718c
Startzeit der fehlerhaften Anwendung: 0x01db5317e3ee9dab
Pfad der fehlerhaften Anwendung: C:\Program Files\Notepad++\notepad++.exe
Pfad des fehlerhaften Moduls: C:\Program Files\Notepad++\plugins\CompressedFileViewer\CompressedFileViewer.dll
Berichtskennung: b7f03e7c-2248-41f4-add9-baa02bed9c1b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by Pascal-Krenckel** [comment]
Can you run the following file, and send me the output. Please copy it into the Plugin directory (C:\Program Files\Notepad++\plugins\CompressedFileViewer\)
[PluginCheck.zip](https://github.com/user-attachments/files/18215786/PluginCheck.zip)

**Comment by mrx1983** [comment]
okay i got further now.
after trying to start the plugincheck it showed in the event viewer that i still not had ".net" installed.
and it gave me a different link. windowsdesktop-runtime-8.0.11-win-x64.exe was the correct installer.
i still got an error output from the plugin check, but notepad++ starts now.
so apparently it was my fault, i installed aspnetcore-runtime-8.0.11-win-x64.exe and dotnet-runtime-8.0.11-win-x64.exe before, but this installers not really installed the correct and needed files apparently.

Program started
C:\Program Files\Notepad++\plugins\CompressedFileViewer\PluginCheck.exe
Notepad++: True
Notepad++: 64-bit

Assembly: CompressedFileViewer.plugin, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null
Native-DLL: True
Dll: 64-bit
Unicode (1): 1
SetInfo
System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Directory.CreateDirectory(String path)
   at CompressedFileViewer.Plugin.LoadSettings() in E:\Programme\CompressedFileViewer\CompressedFileViewer\Plugin.cs:line 193
   at CompressedFileViewer.Plugin.PluginInit() in E:\Programme\CompressedFileViewer\CompressedFileViewer\Plugin.cs:line 58
   at CompressedFileViewer.PluginInfrastructure.UnmanagedExports.SetInfo(NppData notepadPlusData) in E:\Programme\CompressedFileViewer\CompressedFileViewer\PluginInfrastructure\UnmanagedExports.cs:line 20
   at PluginCheck.Program.CheckNativeDll(String dll) in E:\Programme\CompressedFileViewer\PluginCheck\Program.cs:line 85

===========
Finished

**Comment by mrx1983** [comment]
okay it works great now, i added notepad++ as an editor for winscp, and now i can directly edit static br files on my server in one step. really nice plugin.

**Comment by Pascal-Krenckel** [comment]
Yeah, the error message was expected, since the check does not start Notepad++ so the path to the config will be null. But it shows that the plugin does run.
I will update the installation instruction.

**Comment by juanyves** [comment]
As an MRX, I use winscp and Notepad++ as editor. If I try to edit a file from the server with Notepad++, compressedfileviewer tell me that there is no compression and doesn't decompress the file, but if I download the file  through Winscp and open it with Notepad++ then it works correctly. Any idea about the problem ?
